### ISSUE TITLE
use csv files for committees?

### ISSUE THREAD

**Issue by gadanidis** [uoft-lgcu/uoft-lgcu.github.io#20]
Right now the committees are in one large `members.yml` YAML file. This isn't a problem for small committees but for large committees, updating the list seems like it could be a little annoying because you have to rewrite "name: " and "fullname: " a lot.

`_data/members.yml`:
```
twpl_editors: 
    - name: "Fname Lname"
      fullname: "Fname Lname"
    - name: "Fname Lname"
      fullname: "Fname Lname"
    - name: "Fname Lname"
      fullname: "Fname Lname"
   [...]
```

I propose we instead use csv files inside a `committees` subdirectory for committees that have an arbitrary number of members:

`_data/committees/twpl_editors.csv`:
```
name,fullname
Fname Lname,Fname Lname
Fname Lname,Fname Lname
Fname Lname,Fname Lname
[...]
```

(A for-loop that writes out the members' names could interpret the first name listed as the contact person and add the asterisk.)
We could still use the YAML file for positions where there is just one or two members and/or where there are specific positions that matter and not just a list (e.g., for CUPE stewards where there are different stewards per department).

I'm happy to implement this myself, just thought I'd make the issue first in case there are any objections or other ideas.
